# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.Device'),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='disabled', max_length=8),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='disabled', max_length=8),
        ),
    ]
