# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_auto_20170802_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.Device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
